INSERT INTO jokes VALUES (1, "AZ", "Alter Zottel");
INSERT INTO jokes VALUES (2, "AZE", "Auto zu Ende");
INSERT INTO jokes VALUES (3, "B", "Behämmert");
INSERT INTO jokes VALUES (4, "B", "Bescheuert");
INSERT INTO jokes VALUES (5, "B", "Blind");
INSERT INTO jokes VALUES (6, "B", "Bekloppte");
INSERT INTO jokes VALUES (7, "B", "Berliner");
INSERT INTO jokes VALUES (8, "BA", "Blutiger Anfänger");
INSERT INTO jokes VALUES (9, "BB", "Bin blind");
INSERT INTO jokes VALUES (10, "BB", "Blöder Bauer");
INSERT INTO jokes VALUES (11, "BB", "Balla-Balla");
INSERT INTO jokes VALUES (12, "BB", "Bin blöd");
INSERT INTO jokes VALUES (13, "BB", "Bin bekloppt");
INSERT INTO jokes VALUES (14, "BB", "Blinder Bauer");
INSERT INTO jokes VALUES (15, "BC", "Bayrisch Congo");
INSERT INTO jokes VALUES (16, "BC", "Be Careful");
INSERT INTO jokes VALUES (17, "BC", "Bayrischer Chaot");
INSERT INTO jokes VALUES (18, "BC", "Bananenclipper");
INSERT INTO jokes VALUES (19, "BC", "Bauern Club");
INSERT INTO jokes VALUES (20, "BGD", "Bayrische Gebirgsdeppen");
INSERT INTO jokes VALUES (21, "BGL", "Bayrische Gebirgsluschen");
INSERT INTO jokes VALUES (22, "BI", "logisch, oder?");
INSERT INTO jokes VALUES (23, "BI", "Blöder Idiot");
INSERT INTO jokes VALUES (24, "BIT", "Bauer im Tretmobil");
INSERT INTO jokes VALUES (25, "BIT", "Bauer in Trier");
INSERT INTO jokes VALUES (26, "BM", "Bauern-Metropole");
INSERT INTO jokes VALUES (27, "BM", "Bereifter Mörder");
INSERT INTO jokes VALUES (28, "BM", "Beule machen");
INSERT INTO jokes VALUES (29, "BN", "Berlin, Nebenstelle");
INSERT INTO jokes VALUES (30, "BO", "Bekloppter Ochse");
INSERT INTO jokes VALUES (31, "BOR", "Blöder ohne Rückspiegel");
INSERT INTO jokes VALUES (32, "BOR", "Bauer ohne Respekt");
INSERT INTO jokes VALUES (33, "BOR", "Bauer ohne Rücksicht");
INSERT INTO jokes VALUES (34, "BRA", "Braker Restabfall");
INSERT INTO jokes VALUES (35, "BRA", "Bauer rechts ab!");
INSERT INTO jokes VALUES (36, "BRB", "Barbarossas Rhabarber-Barbaren");
INSERT INTO jokes VALUES (37, "BS", "Bald Schrott");
INSERT INTO jokes VALUES (38, "BS", "Besengte Sau");
INSERT INTO jokes VALUES (39, "BU", "Bauer unterwegs");
INSERT INTO jokes VALUES (40, "CLP", "Clericales LumpenPack");
INSERT INTO jokes VALUES (41, "CLP", "Charakterloser Perverser");
INSERT INTO jokes VALUES (42, "CO", "Cheese & Onion");
INSERT INTO jokes VALUES (43, "COE", "Chaos ohne Ende");
INSERT INTO jokes VALUES (44, "COE", "Chaoten ohne Ende");
INSERT INTO jokes VALUES (45, "COE", "Chaot ohne Erbarmen");
INSERT INTO jokes VALUES (46, "COE", "Co-Pilot ohne Eignung");
INSERT INTO jokes VALUES (47, "CW", "Calwer Wildsau");
INSERT INTO jokes VALUES (48, "D", "Depp");
INSERT INTO jokes VALUES (49, "D", "Dumpfbacke");
INSERT INTO jokes VALUES (50, "D", "Doof");
INSERT INTO jokes VALUES (51, "D", "Dussel");
INSERT INTO jokes VALUES (52, "DA", "Dämlicher Anfänger");
INSERT INTO jokes VALUES (53, "DA", "Dauerarschloch");
INSERT INTO jokes VALUES (54, "DA", "Dummer August");
INSERT INTO jokes VALUES (55, "DA", "Dummes Arschloch");
INSERT INTO jokes VALUES (56, "DA", "Dummer Autofahrer");
INSERT INTO jokes VALUES (57, "DAN", "Die armen Nachbarn");
INSERT INTO jokes VALUES (58, "DAN", "Dümmster Autofahrer Niedersachsens");
INSERT INTO jokes VALUES (59, "DAU", "Dummer Autofahrer unterwegs");
INSERT INTO jokes VALUES (60, "DBR", "Dorf bei Rostock");
INSERT INTO jokes VALUES (61, "DD", "Dummer Dussel");
INSERT INTO jokes VALUES (62, "DD", "Doppeldoof");
INSERT INTO jokes VALUES (63, "DE", "Dämlicher Esel");
INSERT INTO jokes VALUES (64, "DE", "Dummer Esel");
INSERT INTO jokes VALUES (65, "DEL", "Deutschlands elende Loser");
INSERT INTO jokes VALUES (66, "DEL", "Dumm-elitärer Luftikus");
INSERT INTO jokes VALUES (67, "DH", "Dummer Hund");
INSERT INTO jokes VALUES (68, "DH", "Doller Hecht");
INSERT INTO jokes VALUES (69, "DL", "Dummer Löffel");
INSERT INTO jokes VALUES (70, "DLG", "Deutschlands letzte Gegend");
INSERT INTO jokes VALUES (71, "DN", "Doofe Nuss");
INSERT INTO jokes VALUES (72, "DO", "Dummer Ochse");
INSERT INTO jokes VALUES (73, "DT", "Dorftrottel");
INSERT INTO jokes VALUES (74, "DU", "Deppen unterwegs");
INSERT INTO jokes VALUES (75, "DU", "Dumpfbacken unterwegs");
INSERT INTO jokes VALUES (76, "DÜW", "Doofe üben wieder");
INSERT INTO jokes VALUES (77, "EBE", "Esel bleibt Esel");
INSERT INTO jokes VALUES (78, "EBE", "Ein blinder Engel");
INSERT INTO jokes VALUES (79, "EBE", "Ein beschränktes Exemplar");
INSERT INTO jokes VALUES (80, "ED", "Entsprungener Depp");
INSERT INTO jokes VALUES (81, "EL", "Entwicklungsland");
INSERT INTO jokes VALUES (82, "EN", "Europas Nieten");
INSERT INTO jokes VALUES (83, "EN", "Europas Narren");
INSERT INTO jokes VALUES (84, "EN", "Entenhausen");
INSERT INTO jokes VALUES (85, "EN", "Europas Nullen");
INSERT INTO jokes VALUES (86, "ERB", "Erbarmen");
INSERT INTO jokes VALUES (87, "ERH", "Erlangen-Hinterland");
INSERT INTO jokes VALUES (88, "ERH", "Ein richtiger Hohlkopf");
INSERT INTO jokes VALUES (89, "ES", "Entflohener Schwabe");
INSERT INTO jokes VALUES (90, "ESW", "Esel sucht Weg");
INSERT INTO jokes VALUES (91, "ESW", "Eine Sau weniger");
INSERT INTO jokes VALUES (92, "ESW", "Eisenach West");
INSERT INTO jokes VALUES (93, "EU", "Esel unterwegs");
INSERT INTO jokes VALUES (94, "EUT", "Esel und Trottel");
INSERT INTO jokes VALUES (95, "F", "Farbenblind");
INSERT INTO jokes VALUES (96, "F", "Fersager");
INSERT INTO jokes VALUES (97, "FD", "Fahrer döst");
INSERT INTO jokes VALUES (98, "FF", "Fahre freihändig");
INSERT INTO jokes VALUES (99, "FF", "Falscher Fuffziger");
INSERT INTO jokes VALUES (100, "FFB", "Fahrer fährt besoffen");
INSERT INTO jokes VALUES (101, "FFB", "Fahrer fährt blind");
INSERT INTO jokes VALUES (102, "FFB", "Fahrst furt Bauer");
INSERT INTO jokes VALUES (103, "FFB", "Führerschein für Blinde");
INSERT INTO jokes VALUES (104, "FFB", "Fünf Flaschen Bier");
INSERT INTO jokes VALUES (105, "FL", "Fliegende Latrine");
INSERT INTO jokes VALUES (106, "FN", "Fahrende Niete");
INSERT INTO jokes VALUES (107, "FO", "Fahrender Ochse");
INSERT INTO jokes VALUES (108, "FO", "Fei Obacht!");
INSERT INTO jokes VALUES (109, "FR", "Fahrender Rollstuhl");
INSERT INTO jokes VALUES (110, "FRG", "Fahren - reine Glückssache");
INSERT INTO jokes VALUES (111, "FRI", "Vorsicht - Riesenidiot!");
INSERT INTO jokes VALUES (112, "FS", "Fährt scheiße");
INSERT INTO jokes VALUES (113, "FTL", "Faul, träge, langsam");
INSERT INTO jokes VALUES (114, "FÜ", "Fahrer übt");
INSERT INTO jokes VALUES (115, "FW", "Freiwild");
INSERT INTO jokes VALUES (116, "GAP", "Geh aufs Pedal!");
INSERT INTO jokes VALUES (117, "GAP", "Größter anzunehmender Penner");
INSERT INTO jokes VALUES (118, "GE", "Großer Esel");
INSERT INTO jokes VALUES (119, "GE", "Goil, ey!");
INSERT INTO jokes VALUES (120, "GF", "Geisterfahrer");
INSERT INTO jokes VALUES (121, "GF", "Gefährlicher Fahrer");
INSERT INTO jokes VALUES (122, "GG", "Große Gefahr");
INSERT INTO jokes VALUES (123, "GK", "Geisteskranker");
INSERT INTO jokes VALUES (124, "GL", "Große Lusche");
INSERT INTO jokes VALUES (125, "GL", "Gesetzlose");
INSERT INTO jokes VALUES (126, "GL", "Gottes Lieblinge");
INSERT INTO jokes VALUES (127, "GL", "Gehirnlose");
INSERT INTO jokes VALUES (128, "GM", "Großer Mist");
INSERT INTO jokes VALUES (129, "GM", "Gemeine Menschen");
INSERT INTO jokes VALUES (130, "GRZ", "Gehirnreduzierte Zone");
INSERT INTO jokes VALUES (131, "GS", "Gesengte Sau");
INSERT INTO jokes VALUES (132, "GS", "Gefährlicher Sonntagsfahrer");
INSERT INTO jokes VALUES (133, "GT", "Gehirntot");
INSERT INTO jokes VALUES (134, "GV", "Gemeiner Verbrecher");
INSERT INTO jokes VALUES (135, "GV", "Geschlechtsverkehr");
INSERT INTO jokes VALUES (136, "GW", "Grausame Wilde");
INSERT INTO jokes VALUES (137, "GW", "Gemeines Wildschwein");
INSERT INTO jokes VALUES (138, "HA", "Hirn abwesend");
INSERT INTO jokes VALUES (139, "HAL", "Hohler aufgeblasener Luftikus");
INSERT INTO jokes VALUES (140, "HAL", "Halbmensch");
INSERT INTO jokes VALUES (141, "HAL", "Hirnamputierter am Lenker");
INSERT INTO jokes VALUES (142, "HAM", "Hinterlistige Autobahnmafia");
INSERT INTO jokes VALUES (143, "HAS", "Henker auf Strassen");
INSERT INTO jokes VALUES (144, "HAS", "Hirsch am Steuer");
INSERT INTO jokes VALUES (145, "HAS", "Höchste Alarmstufe");
INSERT INTO jokes VALUES (146, "HB", "Hilfe Blöde");
INSERT INTO jokes VALUES (147, "HB", "Halb Besoffener");
INSERT INTO jokes VALUES (148, "HB", "Hängebusen");
INSERT INTO jokes VALUES (149, "HB", "Halt Blödies");
INSERT INTO jokes VALUES (150, "HB", "Hein Blöd");
INSERT INTO jokes VALUES (151, "HBN", "Habenichts");
INSERT INTO jokes VALUES (152, "HBS", "Hängebauchschwein");
INSERT INTO jokes VALUES (153, "HBS", "Hinter Braunschweig");
INSERT INTO jokes VALUES (154, "HBS", "Hinter Bosnien");
INSERT INTO jokes VALUES (155, "HD", "Henkers Dienstwagen");
INSERT INTO jokes VALUES (156, "HEF", "Henkers eigenes Fahrzeug");
INSERT INTO jokes VALUES (157, "HEI", "Hilfe, ein Irrer");
INSERT INTO jokes VALUES (158, "HF", "Heiße Fracht");
INSERT INTO jokes VALUES (159, "HF", "Hohle Fratze");
INSERT INTO jokes VALUES (160, "HG", "Höchste Gefahr");
INSERT INTO jokes VALUES (161, "HH", "Hanseatische Hofnarren");
INSERT INTO jokes VALUES (162, "HH", "Halbes Hirn");
INSERT INTO jokes VALUES (163, "HIG", "Informationen geliefert");
INSERT INTO jokes VALUES (164, "hL", "Hirnlose Loser");
INSERT INTO jokes VALUES (165, "HN", "Habenichts");
INSERT INTO jokes VALUES (166, "HO", "Hornochse");
INSERT INTO jokes VALUES (167, "HO", "Halber Ossi");
INSERT INTO jokes VALUES (168, "HOL", "Homos oder Lesben");
INSERT INTO jokes VALUES (169, "HP", "Hortet Pfennige");
INSERT INTO jokes VALUES (170, "HR", "Hirnlose Rindviecher");
INSERT INTO jokes VALUES (171, "HR", "Hessisches Rindvieh");
INSERT INTO jokes VALUES (172, "HRO", "Hier rasen Ossis");
INSERT INTO jokes VALUES (173, "HS", "Hosenscheißer");
INSERT INTO jokes VALUES (174, "HS", "Heute Sonntag");
INSERT INTO jokes VALUES (175, "HS", "Hirnamputierte Sau");
INSERT INTO jokes VALUES (176, "HSK", "Hilfe, Sauerländer kommen");
INSERT INTO jokes VALUES (177, "HSK", "Hilfe, Sie kommen");
INSERT INTO jokes VALUES (178, "HSK", "Homosexuellenkreis");
INSERT INTO jokes VALUES (179, "HSK", "Halb so klug");
INSERT INTO jokes VALUES (180, "HSK", "Hochsauerlandkasper");
INSERT INTO jokes VALUES (181, "HSK", "Homo sucht Kumpel");
INSERT INTO jokes VALUES (182, "HSK", "Hier sterben Kinder");
INSERT INTO jokes VALUES (183, "HU", "Hessisch Uganda");
INSERT INTO jokes VALUES (184, "HU", "Hackklötzchen unterwegs");
INSERT INTO jokes VALUES (185, "HVL", "Hirn Verlust");
INSERT INTO jokes VALUES (186, "HWI", "Halbwegs intelligent");
INSERT INTO jokes VALUES (187, "HWI", "Harnwegsinfektion");
INSERT INTO jokes VALUES (188, "IK", "Idiotenkarre");
INSERT INTO jokes VALUES (189, "IZ", "Idiotenzone");
INSERT INTO jokes VALUES (190, "JEV", "Jeder ein Verrückter");
INSERT INTO jokes VALUES (191, "KA", "Kein Arsch");
INSERT INTO jokes VALUES (192, "KA", "Keine Ahnung");
INSERT INTO jokes VALUES (193, "KB", "Kriegerisches Bergvolk");
INSERT INTO jokes VALUES (194, "KB", "Kuh-Bauer");
INSERT INTO jokes VALUES (195, "KB", "Komplette Blödmänner");
INSERT INTO jokes VALUES (196, "KC", "Keine Chance");
INSERT INTO jokes VALUES (197, "KEH", "Kein eigenes Hirn");
INSERT INTO jokes VALUES (198, "KF", "Kleiner Fisch");
INSERT INTO jokes VALUES (199, "KF", "Krimineller Fahrer");
INSERT INTO jokes VALUES (200, "KG", "Karambolage gefällig?");
INSERT INTO jokes VALUES (201, "KG", "Kein Gehirn");
INSERT INTO jokes VALUES (202, "KH", "Kein Hirn");
INSERT INTO jokes VALUES (203, "KH", "Keine Hemmungen");
INSERT INTO jokes VALUES (204, "KI", "Kaum intelligent");
INSERT INTO jokes VALUES (205, "KLE", "Keiner lenkt elender");
INSERT INTO jokes VALUES (206, "KLE", "Kleines, lebendes Erdferkel");
INSERT INTO jokes VALUES (207, "KN", "Karambolage naht");
INSERT INTO jokes VALUES (208, "KO", "Keine Orientierung");
INSERT INTO jokes VALUES (209, "KR", "Keine Rücksicht");
INSERT INTO jokes VALUES (210, "KR", "Kompromissloser Raser");
INSERT INTO jokes VALUES (211, "KS", "Kracht schon");
INSERT INTO jokes VALUES (212, "KÜN", "Kraftfahrer übt noch");
INSERT INTO jokes VALUES (213, "LAU", "Lauter Arschlöcher unterwegs");
INSERT INTO jokes VALUES (214, "LB", "Lauder Bleede");
INSERT INTO jokes VALUES (215, "LB", "Langer Bachel");
INSERT INTO jokes VALUES (216, "LB", "Lustiger Bursche");
INSERT INTO jokes VALUES (217, "LB", "Langer Bimbo");
INSERT INTO jokes VALUES (218, "LDK", "Land der Kasper");
INSERT INTO jokes VALUES (219, "LDS", "Landkreis Deo-Spray");
INSERT INTO jokes VALUES (220, "LIP", "Lüsterne, impotente Pimmel");
INSERT INTO jokes VALUES (221, "LIP", "Lahme, impotente Person");
INSERT INTO jokes VALUES (222, "LL", "Lalli, Lahmarschiger!");
INSERT INTO jokes VALUES (223, "LL", "Lange Leitung");
INSERT INTO jokes VALUES (224, "LN", "Lachnummer");
INSERT INTO jokes VALUES (225, "LOS", "Lausige Ossis");
INSERT INTO jokes VALUES (226, "LOS", "Loser Operating System");
INSERT INTO jokes VALUES (227, "LOS", "Lenker ohne Schwanz");
INSERT INTO jokes VALUES (228, "LOS", "Land ohne Sonne");
INSERT INTO jokes VALUES (229, "LP", "Lumpenpack");
INSERT INTO jokes VALUES (230, "LS", "Lästiger Sauerländer");
INSERT INTO jokes VALUES (231, "LU", "Loser unterwegs");
INSERT INTO jokes VALUES (232, "LWL", "Leberwurstland");
INSERT INTO jokes VALUES (233, "M", "Muffel");
INSERT INTO jokes VALUES (234, "MA", "Müll-Abfuhr");
INSERT INTO jokes VALUES (235, "MA", "Masturbierendes Arschloch");
INSERT INTO jokes VALUES (236, "ME", "Meisterhafter Extremalfahrkünstler");
INSERT INTO jokes VALUES (237, "ME", "Marke Eigenbau");
INSERT INTO jokes VALUES (238, "ME", "Motorisierter Esel");
INSERT INTO jokes VALUES (239, "MEI", "Mit eingeschränkter Intelligenz");
INSERT INTO jokes VALUES (240, "MHL", "Mielkes Handlanger");
INSERT INTO jokes VALUES (241, "MK", "Märkischer Knallkopf");
INSERT INTO jokes VALUES (242, "MK", "Massenkarambolage");
INSERT INTO jokes VALUES (243, "MK", "Meckerkopp");
INSERT INTO jokes VALUES (244, "MK", "Mistkutscher");
INSERT INTO jokes VALUES (245, "MK", "Märkisch Kongo");
INSERT INTO jokes VALUES (246, "MK", "Matschköpfe");
INSERT INTO jokes VALUES (247, "MOL", "Moldawien");
INSERT INTO jokes VALUES (248, "MOL", "Meine Oma lenkt");
INSERT INTO jokes VALUES (249, "MOS", "Müde oder schläfrig");
INSERT INTO jokes VALUES (250, "MSP", "Macht sie platt");
INSERT INTO jokes VALUES (251, "MSP", "Mir san prima");
INSERT INTO jokes VALUES (252, "MSP", "Mama sucht Papa");
INSERT INTO jokes VALUES (253, "MSP", "Mein Schwein piepst");
INSERT INTO jokes VALUES (254, "MTK", "Meine tolle Knautschzone");
INSERT INTO jokes VALUES (255, "MTK", "Miese Tunten kommen");
INSERT INTO jokes VALUES (256, "MTK", "Mir traut keiner");
INSERT INTO jokes VALUES (257, "MTK", "Mülltonnenkutscher");
INSERT INTO jokes VALUES (258, "MTL", "Mutantenland");
INSERT INTO jokes VALUES (259, "MZ", "Miese Zicke");
INSERT INTO jokes VALUES (260, "MZ", "Mieser Zipfel");
INSERT INTO jokes VALUES (261, "NAU", "Nur Anfänger unterwegs");
INSERT INTO jokes VALUES (262, "NDH", "Nicht deutscher Herkunft");
INSERT INTO jokes VALUES (263, "NE", "Null Erfahrung");
INSERT INTO jokes VALUES (264, "NEA", "Neandertaler");
INSERT INTO jokes VALUES (265, "NES", "Nahezu erloschenes Sehvermögen");
INSERT INTO jokes VALUES (266, "NEW", "Noch ein Wahnsinniger");
INSERT INTO jokes VALUES (267, "NEW", "Noch ein Wichser");
INSERT INTO jokes VALUES (268, "NF", "Nicht füttern");
INSERT INTO jokes VALUES (269, "NF", "Neufundland");
INSERT INTO jokes VALUES (270, "NF", "Nordferkel");
INSERT INTO jokes VALUES (271, "NI", "Nur Idioten");
INSERT INTO jokes VALUES (272, "NMS", "Nur müde Schleicher");
INSERT INTO jokes VALUES (273, "NOH", "Noch ohne Hirn");
INSERT INTO jokes VALUES (274, "NOH", "Nutten ohne Hosen");
INSERT INTO jokes VALUES (275, "NOM", "Nicht ohne Mutti");
INSERT INTO jokes VALUES (276, "NOM", "Nimm Oma mit");
INSERT INTO jokes VALUES (277, "NU", "Niete unterwegs");
INSERT INTO jokes VALUES (278, "NVP", "Noch vor Polen");
INSERT INTO jokes VALUES (279, "NW", "Nackte Wahnsinnige");
INSERT INTO jokes VALUES (280, "NWM", "Niemand will mich");
INSERT INTO jokes VALUES (281, "OA", "Oberarsch");
INSERT INTO jokes VALUES (282, "OAL", "Oberarschloch");
INSERT INTO jokes VALUES (283, "OB", "Ohne Bremsen");
INSERT INTO jokes VALUES (284, "OBG", "Obergauner");
INSERT INTO jokes VALUES (285, "OD", "Ohne Durchblick");
INSERT INTO jokes VALUES (286, "OD", "Oller Dussel");
INSERT INTO jokes VALUES (287, "OE", "Ohne Erbarmen");
INSERT INTO jokes VALUES (288, "OE", "Oller Esel");
INSERT INTO jokes VALUES (289, "OE", "Ohne Erfahrung");
INSERT INTO jokes VALUES (290, "OF", "Ohne Fahrkenntnisse");
INSERT INTO jokes VALUES (291, "OF", "Ohne Führerschein");
INSERT INTO jokes VALUES (292, "OG", "Oh Grauen");
INSERT INTO jokes VALUES (293, "OG", "Ohne Gehirn");
INSERT INTO jokes VALUES (294, "OG", "Ohne Geld");
INSERT INTO jokes VALUES (295, "OH", "Ohne Hirn");
INSERT INTO jokes VALUES (296, "OHA", "Oberharzer Affe");
INSERT INTO jokes VALUES (297, "OHV", "Ohne Hirn - Verstand");
INSERT INTO jokes VALUES (298, "OHZ", "Ohne Hirn zugelassen");
INSERT INTO jokes VALUES (299, "OHZ", "Ochsen hinterm Zaun");
INSERT INTO jokes VALUES (300, "OL", "Ordentliche Leute");
INSERT INTO jokes VALUES (301, "OL", "Oller Lahmarsch");
INSERT INTO jokes VALUES (302, "OL", "Oller Lümmel");
INSERT INTO jokes VALUES (303, "OVP", "Ohne vernünftige Perspektive");
INSERT INTO jokes VALUES (304, "OR", "Oberrindvieh");
INSERT INTO jokes VALUES (305, "OR", "Ohne Rücksicht");
INSERT INTO jokes VALUES (306, "OS", "Ohne Stadtplan");
INSERT INTO jokes VALUES (307, "OS", "Oberschwuchtel");
INSERT INTO jokes VALUES (308, "OS", "Oberstes Schwein");
INSERT INTO jokes VALUES (309, "OS", "Olle Schwuchtel");
INSERT INTO jokes VALUES (310, "OS", "Ohne Sicherheiten");
INSERT INTO jokes VALUES (311, "OS", "Ordinäre Sau");
INSERT INTO jokes VALUES (312, "OVL", "Ochs vom Land");
INSERT INTO jokes VALUES (313, "PB", "Pausenlos Besoffen");
INSERT INTO jokes VALUES (314, "PE", "Peinliche Erleuchtung");
INSERT INTO jokes VALUES (315, "PE", "Personifiziertes Elend");
INSERT INTO jokes VALUES (316, "PI", "Pennt immer");
INSERT INTO jokes VALUES (317, "PI", "Provinzidiot");
INSERT INTO jokes VALUES (318, "PI", "Perverse Irre");
INSERT INTO jokes VALUES (319, "PLÖ", "Pennt leider öfter");
INSERT INTO jokes VALUES (320, "PS", "Pfälzisch-Sibirien");
INSERT INTO jokes VALUES (321, "QLB", "Qualvoll lebende Bevölkerung");
INSERT INTO jokes VALUES (322, "QLB", "Querlenkender Blödmann");
INSERT INTO jokes VALUES (323, "RAS", "Rambo am Steuer");
INSERT INTO jokes VALUES (324, "RD", "Richtiger Dussel");
INSERT INTO jokes VALUES (325, "RD", "Rundum dämlich");
INSERT INTO jokes VALUES (326, "RE", "Rettet euch");
INSERT INTO jokes VALUES (327, "RE", "Rambos Erleuchtung");
INSERT INTO jokes VALUES (328, "PM", "Posemuckel");
INSERT INTO jokes VALUES (329, "RO", "Rasender Ochse");
INSERT INTO jokes VALUES (330, "ROW", "Rum oder Whisky");
INSERT INTO jokes VALUES (331, "RS", "Rammt Sie");
INSERT INTO jokes VALUES (332, "RS", "Rasende Sau");
INSERT INTO jokes VALUES (333, "RS", "Rollender Sarg");
INSERT INTO jokes VALUES (334, "RS", "Ruhe sanft");
INSERT INTO jokes VALUES (335, "RT", "Reine Taktik");
INSERT INTO jokes VALUES (336, "RV", "Rasende Verlierer");
INSERT INTO jokes VALUES (337, "RZ", "Rüde Zeitgenossen");
INSERT INTO jokes VALUES (338, "RZ", "Rübenzüchter");
INSERT INTO jokes VALUES (339, "RZ", "Rasende Zombies");
INSERT INTO jokes VALUES (340, "RZ", "Richtige Zauderer");
INSERT INTO jokes VALUES (341, "SAD", "Sadisten");
INSERT INTO jokes VALUES (342, "SAD", "Sau auf Durchfahrt");
INSERT INTO jokes VALUES (343, "SAD", "Sieht alles doppelt");
INSERT INTO jokes VALUES (344, "SBK", "Saublöder Kraftfahrer");
INSERT INTO jokes VALUES (345, "SDH", "Sippe der Hampelmänner");
INSERT INTO jokes VALUES (346, "SC", "Super Cool");
INSERT INTO jokes VALUES (347, "SE", "Schläft ewig");
INSERT INTO jokes VALUES (348, "SFA", "Sie fieses Arschloch");
INSERT INTO jokes VALUES (349, "SFA", "Sau fährt Auto");
INSERT INTO jokes VALUES (350, "SFA", "Säufer fährt Auto");
INSERT INTO jokes VALUES (351, "SFA", "So fahren Arschlöcher");
INSERT INTO jokes VALUES (352, "SHG", "Säufer, Huren und Ganoven");
INSERT INTO jokes VALUES (353, "SHG", "Sozialhilfe Gebiet");
INSERT INTO jokes VALUES (354, "SHL", "Sonntagsfahrer hält Lenkrad");
INSERT INTO jokes VALUES (355, "SI", "Superidiot");
INSERT INTO jokes VALUES (356, "SI", "Suche Intelligenz");
INSERT INTO jokes VALUES (357, "SLS", "Saarländische Lenkradsau");
INSERT INTO jokes VALUES (358, "SLZ", "Stirb langsam, Zoni!");
INSERT INTO jokes VALUES (359, "SON", "Sonntagsfahrer");
INSERT INTO jokes VALUES (360, "SP", "Spinner pennen");
INSERT INTO jokes VALUES (361, "ST", "Sicherer Tod");
INSERT INTO jokes VALUES (362, "ST", "Stiertreiber");
INSERT INTO jokes VALUES (363, "ST", "Stocktaub");
INSERT INTO jokes VALUES (364, "ST", "Straßentrottel");
INSERT INTO jokes VALUES (365, "ST", "Süd-Texas");
INSERT INTO jokes VALUES (366, "STA", "Scheiße, totaler Anfänger!");
INSERT INTO jokes VALUES (367, "STD", "Sie töten Dich");
INSERT INTO jokes VALUES (368, "STL", "Sachsens trotteligster Landkreis");
INSERT INTO jokes VALUES (369, "SU", "Sau unterwegs");
INSERT INTO jokes VALUES (370, "SU", "Sicherer Unfall");
INSERT INTO jokes VALUES (371, "SU", "Sonntagsfahrer unterwegs");
INSERT INTO jokes VALUES (372, "SU", "Suche Unfall");
INSERT INTO jokes VALUES (373, "TBB", "Taub, blöd, blind");
INSERT INTO jokes VALUES (374, "TBB", "Tausend blinde Bauern");
INSERT INTO jokes VALUES (375, "TF", "Tiefflieger");
INSERT INTO jokes VALUES (376, "TF", "Trabbifahrer");
INSERT INTO jokes VALUES (377, "TIR", "Trottel im Regen");
INSERT INTO jokes VALUES (378, "TIR", "Tod im Rücken");
INSERT INTO jokes VALUES (379, "UN", "Unfall naht");
INSERT INTO jokes VALUES (380, "UN", "Unsere Narren");
INSERT INTO jokes VALUES (381, "UN", "Unsere Nieten");
INSERT INTO jokes VALUES (382, "VB", "Vollkommene Blödmänner");
INSERT INTO jokes VALUES (383, "VEC", "Verblödeter Elchclub");
INSERT INTO jokes VALUES (384, "VGL", "Vorsicht, gestern losgefahren");
INSERT INTO jokes VALUES (385, "VIE", "Vollidiot im Einsatz");
INSERT INTO jokes VALUES (386, "VIE", "Vollidiot in Eile");
INSERT INTO jokes VALUES (387, "VRS", "Vorsicht, radikaler Schnellbremser");
INSERT INTO jokes VALUES (388, "VS", "Verirrter Schwachkopf");
INSERT INTO jokes VALUES (389, "VS", "Verkehrs-Sau");
INSERT INTO jokes VALUES (390, "WAF", "Wech aussa Fahrbahn");
INSERT INTO jokes VALUES (391, "WAF", "Wessen Affe fährt");
INSERT INTO jokes VALUES (392, "WAF", "Westfälischer Amok-Fahrer");
INSERT INTO jokes VALUES (393, "WAF", "Wie Affen Ficken ");
INSERT INTO jokes VALUES (394, "WAF", "Wildschwein auf Futtersuche");
INSERT INTO jokes VALUES (395, "WAF", "Wilder Affe fährt");
INSERT INTO jokes VALUES (396, "WAK", "Wessi-Abwehr-Kommando");
INSERT INTO jokes VALUES (397, "WBS", "War bei Stasi");
INSERT INTO jokes VALUES (398, "WEM", "Wieder ein Mistbauer");
INSERT INTO jokes VALUES (399, "WES", "Wahnsinnig, eigenwillig, schnell");
INSERT INTO jokes VALUES (400, "WES", "Was ein Spinner");
INSERT INTO jokes VALUES (401, "WF", "Wilder Fahrer");
INSERT INTO jokes VALUES (402, "WHV", "Wir haben Vorfahrt");
INSERT INTO jokes VALUES (403, "WHV", "Wir hinterlassen Verletzte");
INSERT INTO jokes VALUES (404, "WL", "Wahnsinniger Landwirt");
INSERT INTO jokes VALUES (405, "WL", "Wildgewordener Landstreicher");
INSERT INTO jokes VALUES (406, "WN", "Wahnsinnig neurotisch");
INSERT INTO jokes VALUES (407, "WN", "Wahnsinniger Narr");
INSERT INTO jokes VALUES (408, "WOB", "Wilder ohne Bildung");
INSERT INTO jokes VALUES (409, "WST", "Wir saufen trotzdem");
INSERT INTO jokes VALUES (410, "WST", "Wir stechen Torf");
INSERT INTO jokes VALUES (411, "WST", "Wir sind Töffel");
INSERT INTO jokes VALUES (412, "WST", "Wir sammeln Tote");
INSERT INTO jokes VALUES (413, "WTM", "Wir töten Menschen");
INSERT INTO jokes VALUES (414, "WTM", "Wir trinken Milch");
INSERT INTO jokes VALUES (415, "WÜ", "Weiter üben");
INSERT INTO jokes VALUES (416, "WUG", "Windbeutel und Gauner");
INSERT INTO jokes VALUES (417, "WW", "Wilder Wutz");
INSERT INTO jokes VALUES (418, "WW", "Wildes Wichtelchen");
INSERT INTO jokes VALUES (419, "WZL", "Wanzen, Zecken, Läuse");
INSERT INTO jokes VALUES (420, "ZE", "Zum Erbarmen");
INSERT INTO jokes VALUES (421, "ZS", "Ziemlich scheiße");
